spring.application.name=attendance-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance-service
spring.datasource.username=postgres
spring.datasource.password=2002
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.gateway.routes[1].id=attendance-service
spring.cloud.gateway.routes[1].uri=lb://ATTENDANCE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/attendance/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
