spring.application.name=employee-service
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/employee-service
spring.datasource.username=postgres
spring.datasource.password=2002
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.gateway.routes[2].id=employee-service
spring.cloud.gateway.routes[2].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/employee/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
